{
 "title": "Rock-Paper-Scissors Game",
 "description": "A dashboard that solely focusses on metrics regarding the actual game statistics.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Stats",
   "type": "piechart",
   "description": "The users' game results.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(result) (rps_play_total)"
    }
   ]
  },
  {
   "title": "Total Plays",
   "type": "stat",
   "description": "Number of plays between users and server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rps_play_total)" }
   ]
  },
  { "title": "Moves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "User Moves",
   "type": "bargauge",
   "description": "The total number of moves chosen by the player, ordered by move type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(user) (rps_play_total)" }
   ]
  },
  {
   "title": "Server Moves",
   "type": "bargauge",
   "description": "The total number of moves chosen by the server,\nordered by move type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (rps_play_total)"
    }
   ]
  },
  { "title": "Combinations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Play Combinations",
   "type": "bargauge",
   "description": "Contains all combinations of plays and their respective occurrence.\nThe legend's first value is the user's move, the second belongs to the server. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rps_play_total", "legendFormat": "{{user}} vs {{server}}" }
   ]
  }
 ]
}