
services:

  traefik:
    image: "traefik:v3.0"
    container_name: "reverse-proxy"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.rpsresolver.acme.httpchallenge=true"
#      - "--certificatesresolvers.rpsresolver.acme.httpchallenge.entrypoint=web"
#      - "--certificatesresolvers.rpsresolver.acme.email=lafilor@icloud.com"
#      - "--certificatesresolvers.rpsresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      #- "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    image: "filor.com/rps-backend"
    container_name: "rps-backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      #- "traefik.http.routers.backend.tls.certresolver=rpsresolver"

  frontend:
    image: "filor.com/rps-frontend"
    container_name: "rps-frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      #- "traefik.http.routers.frontend.tls.certresolver=rpsresolver"
